# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-03 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labourinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('user_invitation_code', models.CharField(max_length=100)),
                ('followers', models.ManyToManyField(blank=True, null=True, related_name='_labourinfo_followers_+', to='labours.Labourinfo')),
                ('following', models.ManyToManyField(blank=True, null=True, related_name='_labourinfo_following_+', to='labours.Labourinfo')),
            ],
        ),
    ]
