# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2010-12-30 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labours', '0002_auto_20101231_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='userfollowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='labourinfo',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='labourinfo',
            name='following',
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='followers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_followers', to='labours.Labourinfo'),
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='following',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_following', to='labours.Labourinfo'),
        ),
    ]
