# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-11 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labours', '0004_auto_20211209_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labourpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labour_image', models.ImageField(upload_to='')),
                ('labourer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labours.Labourinfo')),
            ],
        ),
    ]
