# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-11 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labours', '0006_auto_20211211_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourpost',
            name='labour_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
