# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-12 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labours', '0009_labourinfo_user_post_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='labourinfo',
            name='max_post_count',
            field=models.IntegerField(default=1),
        ),
    ]
